"""categoryID in posts

Revision ID: 5832970d2889
Revises: 38886c2274f0
Create Date: 2026-02-21 23:02:09.976311

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5832970d2889'
down_revision: Union[str, Sequence[str], None] = '38886c2274f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('category_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'posts', 'category', ['category_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.drop_column('posts', 'category_id')
    # ### end Alembic commands ###
